image: docker:stable

options:
  docker: true
pipelines:
  default:
    - step:
        services:
          - docker
        script: # Modify the commands below to build your repository.
          # authenticate with the Docker Hub registry
          - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
          - export IMAGE_NAME=$DOCKER_HUB_ORG/splunk-appbuilder:$BITBUCKET_COMMIT
          # build the Docker image (this will use the Dockerfile in the root of the repo)
          - docker build -t $IMAGE_NAME -t $DOCKER_HUB_ORG/splunk-appbuilder:develop .
          # push the new Docker image to the Docker registry
          - docker push $IMAGE_NAME
          - docker push $DOCKER_HUB_ORG/splunk-appbuilder:develop
  branches:
    master:
          - step:
              services:
                - docker
              script: # Modify the commands below to build your repository.
                # authenticate with the Docker Hub registry
                - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
                  # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
                - export IMAGE_NAME=$DOCKER_HUB_ORG/splunk-appbuilder:$BITBUCKET_COMMIT
                # build the Docker image (this will use the Dockerfile in the root of the repo)
                - docker build -t $IMAGE_NAME -t $DOCKER_HUB_ORG/splunk-appbuilder:latest .
                # push the new Docker image to the Docker registry
                - docker push $IMAGE_NAME
                - docker push $DOCKER_HUB_ORG/splunk-appbuilder:latest
    release/*:
          - step:
              services:
                - docker
              script: # Modify the commands below to build your repository.
                # authenticate with the Docker Hub registry
                - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
                  # Set $DOCKER_HUB_USERNAME and $DOCKER_HUB_PASSWORD as environment variables in repository settings
                - export IMAGE_NAME=$DOCKER_HUB_ORG/splunk-appbuilder:$BITBUCKET_COMMIT
                # build the Docker image (this will use the Dockerfile in the root of the repo)
                - docker build -t $IMAGE_NAME -t $DOCKER_HUB_ORG/splunk-appbuilder:beta .
                # push the new Docker image to the Docker registry
                - docker push $IMAGE_NAME
                - docker push $DOCKER_HUB_ORG/splunk-appbuilder:beta

