#!/usr/bin/python3
# -*- coding: utf-8 -*-
import os
from junitparser import JUnitXml, Failure, Skipped, Error

def main():
    passed = True
    path = 'test-reports'
    reports = os.listdir(path)
    for report in reports:
        xmlfile = os.path.join(path, report)
        xml = JUnitXml.fromfile(xmlfile)
        for suite in xml:
            for case in suite:
                if case.result:
                    if isinstance(case.result, Failure):
                        passed = False
                        print("FAILED! {}/{}".format(case.classname, case.name))
    if not passed:
        exit(1)
main()

